### ISSUE TITLE
Euroscoupe Autofill für descend kapput

### ISSUE THREAD

**Issue by Balu1412** [VATGER-Nav/EDWW-Package-East#130]
https://gyazo.com/db4c2d46871dc899a61e5f7b67ed3bcf

Aktuelle höhe 4000f, geändert zu 3000f. Autofill macht das wenn man es auswählt:
"Descend to altitude 4000 ft ft, QNH 1029.3000"
Dies passiert bei allen höhen Anweisungen, die alte Höhe wird an die Stelle eingefügt wo eigentlich die neue hin muss. Die neue Höhe wird aber einfach dahinter gesetzt.

**Comment by hannesaltmann** [comment]
Fixed mit dem nächsten AIRAC release
