### ISSUE TITLE
Allow Tower Profile to change speed assignments 

### ISSUE THREAD

**Issue by ascarion** [VATGER-Nav/EDWW-Package-East#131]
With new SOP changes, Berlin Tower is now allowed to change speed assignments of aircraft within their airspace. Tower controllers should thus be able manage the assigned speed in aircraft tags.
This would potentially also help arrival/director to adjust to tower's speed assignments.

**Comment by ascarion** [comment]
When no speed is assigned, Tower can still not enter speeds. Maybe the menu could also be made to open when clicked on indicated speed.

**Comment by hannesaltmann** [comment]
@ManuelPick
