### ISSUE TITLE
[EDWW] Berlin Airspace C auto activation

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/EDWW-Package-East#142]
Disable the auto-deactivation of the AS-C Berlin Map on CTR positions when Arrival comes online after providing Top-Down services.
While I understand the use of it to have a decluttered radar screen, when having an inbound rush and EDDB_APP comes online to reliev, no further turns onto the ILS nor descent instructions can be given due to not having any sort of reference points on the radar anymore (not even the extended centerlines).
I think the manual activation and deactivation is not that complicated, but in situations like the one described you really dont want to be searching your TopSky Maps folder for it and rather choose a calm second to activate/deactivate it.

**Comment by hannesaltmann** [comment]
We believe that in most cases, this will require the airspace to be disabled instead of being enabled. Therefore this feature will stay as it is currently. 
If the APP comes online, CTR can always enable airspace C in a matter of seconds.
