### ISSUE TITLE
[EDWW] Update Sectorlines

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/EDWW-Package-East#144]
Sieht nicht ganz so perfekt aus, wie es aussehen könnte... 😛 

- Make all sectors a single grid and the upper sectors cover the same coordinates where applicable 

![grafik](https://github.com/VATGER-Nav/EDWW-Package-East/assets/62181068/efde40cf-cac2-47de-b75e-4af106133f40)
![grafik](https://github.com/VATGER-Nav/EDWW-Package-East/assets/62181068/2cd2f31b-0908-4bd9-80bb-9711eafcd2f4)

Ich kann da mal selber reinschauen, wenn ihr wollt

**Comment by hannesaltmann** [comment]
See beta package: https://github.com/VATGER-Nav/edww-package/issues/42
