### ISSUE TITLE
[Tag file, Center profile] Heading requests not coming through

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/EDWW-Package-East#53]
With the new TopSky version, system requests for headings are not shown to the upstream sector because the requests are now only highlighted in the respective tag item (speed, heading (rate?)) and not in the general coordination request item in the first line of the tag. Therefore, since the current item is a Euroscope tag item, they are not shown anymore. System coordination requests by downstream controllers can be checked in the message-in window though, but in situations of high traffic the "coordination request"-sound can be easily overheard and in my opinion that is not sufficient. 
I always liked the heading draw tool to enter and measure appropriate turn-rates, but in this case I think the importance of the request function prevails and the tag item should be either changed to the TopSky plugin/AHDG or an alternative solution should be found.

**Comment by bilalshaikh292** [comment]
Heyy I would Like to Contribute ?

**Comment by ManuelPick** [comment]
Might work in newest Topsky Beta. RTI request to different controller shows up in COPX. So far unable to test incoming RTI.
