### ISSUE TITLE
[EDUU] Update TopSky Maps tactical directs

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/EDWW-Package-East#60]
Update `MAP:TACTICAL DIRECTS / FOLDER:LOA LEVEL INFO` to match [Maastricht-Karlsruhe LoA](https://dms.vatsim-germany.org/s/BgjLcEnFSpXtL85) section 4.2

**Comment by hannesaltmann** [comment]
Fixed with release of AIRAC2308
