### ISSUE TITLE
[TopSky Maps] Add Jet Departure and Approach procedures according to VAD

### ISSUE THREAD

**Issue by lucianoasmus** [VATGER-Nav/EDWW-Package-East#66]
Add Jet Departure and Approach procedures according to VAD to TopSky VFR-Fixes Map (alt+v)
•For ETSH
•For ETNL

**Comment by lucianoasmus** [comment]
@hannesaltmann kann ich dir die Tage auch direkt selber machen wenn du möchtest.

**Comment by hannesaltmann** [comment]
Ja gern! Mach einfach einen Pull Request, wenn du das fertig hast :)
