### ISSUE TITLE
[AIRAC 2308] Update NOTAMs

### ISSUE THREAD

**Issue by hannesaltmann** [VATGER-Nav/EDWW-Package-East#76]
On AIRAC release, all NOTAMs shall be updated (Forum + Groundradar Plugin)

- [x] Update Forum NOTAMs
- [x] Update GRP Maps

**Comment by hannesaltmann** [comment]
https://board.vatsim-germany.org/threads/notams-edww-region-east.70614/

**Comment by ManuelPick** [comment]
Forum NOTAMs updated, kein Change in GRP Maps benötigt.
