### ISSUE TITLE
Update EDDB Ground Layout

### ISSUE THREAD

**Issue by ManuelPick** [VATGER-Nav/EDWW-Package-East#79]
The current EDDB ground layout is based on the DFS chart. With new satellite imagery, the layout can be adjusted to closer resemble RL and the ground taxi network.

**Comment by hannesaltmann** [comment]
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/06cda890-5097-448e-841d-980852b2ddab)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/fa4ab3b9-99e3-4914-82de-f53ba5b9dcbf)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/fa5a6d3b-17ab-43e2-857b-1f4aa756a57e)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/d6dd0366-7bf1-449d-8ba7-fb76e1389b4e)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/fb7df750-cf50-40ff-bb4c-1314e15f6814)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/6da6c00c-f812-4711-b6a4-88f39b9231f6)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/9d566d7a-b1fe-48b0-ad64-dd678bdc9390)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/09c0bc99-fea8-4ea6-a7b8-16836f96b4ed)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/71515220/fcca63c8-d843-4227-913d-105d75dd5c2c)

**Comment by ManuelPick** [comment]
Updated current Layout, DFS Layout WIP

**Comment by ManuelPick** [comment]
Moved to new Pack.
