### ISSUE TITLE
More waypoints in CTR ASR

### ISSUE THREAD

**Issue by ManuelPick** [VATGER-Nav/EDWW-Package-East#85]
![grafik](https://github.com/VATGER-Nav/EDWW-Package-East/assets/40025269/02785791-a259-4e3b-a718-42cb2728ec16)

**Comment by hannesaltmann** [comment]
Bei APP haben sie das nicht. Kann man vlt. als Aktivierung machen.

**Comment by ManuelPick** [comment]
Ja entweder das oder über das Login callsign geht es auch oder?

**Comment by hannesaltmann** [comment]
Ja genau, daran hatte ich gedacht. Soll halt bei CTR angezeigt werden und bei APP nicht :)

**Comment by ManuelPick** [comment]
Check, kümmere ich mich zu 2309 drum.

**Comment by hannesaltmann** [comment]
Ich könnte Quentin mal nach mehr Infos fragen

**Comment by ManuelPick** [comment]
Klingt gut, sofern ich weiß sind es alle WPTs die auf den Airways sind.

**Comment by hannesaltmann** [comment]
Jo alle auf den Airways.

**Comment by hannesaltmann** [comment]
Vlt. könnte man es noch so einstellen, dass man mit einem Hotkey dann die Wegpunkte easy ausblenden kann, falls sie mal stören sollte.
