### ISSUE TITLE
Alias command nutzt QNH des DEP Airports

### ISSUE THREAD

**Issue by Balu1412** [VATGER-Nav/EDWW-Package-East#93]
Habe einem Text Flieger über das ES Menü einen descend auf 4000f gegeben, die Nachricht die dabei ausgefüllt wurde hab ich abgesendet und anschließend bemerkt das die Nachricht das QNH des dep Airport genutzt hat (QNH Berlin: 1019, in der Nachricht QNH 1018 (EDDN)). Bei weiteren descends wurde weiterhin das EDDN QNH eingesetzt.
Ein Mal war in der Nachricht die QNH source sichtbar in der EDDN stand, was der dep airport des jeweiligen Fliegers war.

**Comment by ManuelPick** [comment]
Konnte ich so nicht nachvollziehen, habe es getestet und immer den korrekten QNH bekommen.

**Comment by hannesaltmann** [comment]
> Konnte ich so nicht nachvollziehen, habe es getestet und immer den korrekten QNH bekommen.

Ggf. ES Bug, weil EDDN (mit allen Procs...) als aktiver Airport in unserem Sectorfile ist?
