### ISSUE TITLE
[ETSH] Fehlende Anflüge

### ISSUE THREAD

**Issue by Balu1412** [VATGER-Nav/EDWW-Package-East#99]
In Holdorf fehlen mehrere Anflüge in ES, z.B. die RNP‘s.

**Comment by hannesaltmann** [comment]
Fehlen die SIDs auch?

**Comment by Balu1412** [comment]
Nein, nur ein paar approches.
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/77582471/b4f7bd68-65df-445d-84d7-5402064865d6)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/77582471/6d618bbe-825d-490d-bf5a-62c1eb586e88)
![image](https://github.com/VATGER-Nav/EDWW-Package-East/assets/77582471/4f0729aa-45e9-41d6-bcb3-091a86fda091)

**Comment by hannesaltmann** [comment]
Die fehlenden Approaches sind mit dem nächsten AIRAC Release dabei.
